server:
  port: 8081

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      # Mỗi lần chạy sẽ tạo 1 Group ID ngẫu nhiên để tất cả các Node cùng nhận được tin
      group-id: ${GROUP_ID:group-default}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer